title: Abhay M
logo: WhatsApp Image 2025-06-06 at 4.05.22 PM.jpeg
theme: jekyll-theme-minimal
text: https://github.com/abhaym2255/Abhay_portfolio/blob/48eacf648ff90c7c065acb0184616629310ef3c1/README.md
